@Library('cicd') _
def cipipeline = new opstree.ci.templates.java_ci.java_ci()
node {
  
  cipipeline.call([

    // WORKSPACE MANAGEMENT
    clean_workspace: true,
    ignore_clean_workspace_failure: false,
    delete_dirs: false,
    clean_when_build_aborted: true, 
    clean_when_build_failed: true,
    clean_when_not_built: true,
    clean_when_build_succeed: true,
    clean_when_build_unstable: true,

    // VCS MANAGEMENT 
    repo_https_url: "https://scm.ecomexpress.in/scm/~ayush.k_ecomexpress.in/ayush-lastmile2.0.git",
    repo_ssh_url: "https://scm.ecomexpress.in/scm/~ayush.k_ecomexpress.in/ayush-lastmile2.0.git",
    repo_branch: "master",
    repo_url_type: "http",
    jenkins_git_creds_id: "github-token",
    source_code_path: "",

    // Creds Scanning
    gitleaks_check: true,
    fail_job_if_leak_detected: false,
    gitleaks_report_format: "json",
    gitleaks_report_jenkins_publish: true,

    perform_code_build: true,
    build_tool: "",
    pom_location: " ",
    mvn_settings_path: "",

    // Notification
    
    notification_enabled: true,
    notification_channel: "teams",
    webhook_url_creds_id: "teams_webhook"
  ])

}
